
name: Build
on: [push, pull_request]

env:
  DOTNET_NOLOGO: 1

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x.x
            8.x.x

      - name: Restore Fody
        run: dotnet restore Fody.sln

      - name: Build Fody
        run: dotnet build --configuration Release --no-restore Fody.sln

      - name: Test Fody
        run: dotnet test --configuration Release --no-build Fody.sln

      - name: Restore Integration
        run: dotnet restore Integration/Integration.sln

      - name: Build Integration
        run: dotnet build --configuration Release --no-restore Integration/Integration.sln

      - name: Test Integration
        run: dotnet test --configuration Release --no-build Integration/Integration.sln

      - name: Upload NuGet
        uses: actions/upload-artifact@v4
        with:
          name: NuGet
          path: nugets/*.nupkg

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x.x
            8.x.x

      - name: Restore Fody
        run: dotnet restore Fody.sln

      - name: Build Fody
        run: dotnet build --configuration Release --no-restore Fody.sln

# TODO Uncomment this when tests pass on Linux
#      - name: Test Fody
#        run: dotnet test --configuration Release --framework net8.0 --no-build Fody.sln

      - name: Restore Integration
        run: dotnet restore Integration/Integration.sln

      - name: Build Integration
        run: dotnet build --configuration Release --no-restore Integration/Integration.sln

      - name: Test Integration
        run: dotnet test --configuration Release --framework net6.0 --no-build Integration/Integration.sln

  windows-vs:
    name: Windows VS
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup VS Dev Tools
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Environment
        run: echo 'Platform=' >> $GITHUB_ENV
        shell: bash

      - name: Build Fody
        run: msbuild -restore Fody.sln /p:Configuration=Release /verbosity:minimal

      - name: Test Fody
        run: vstest.console Tests/bin/Release/net48/Tests.dll

      - name: Build Integration
        run: msbuild -restore Integration/Integration.sln /p:Configuration=Release /verbosity:minimal

      - name: Test Integration
        run: vstest.console Integration/Tests/bin/Release/net472/Tests.dll
